// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcserver.proto

// Protobuf Java Version: 3.25.1
package com.maralana;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maralana.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
