// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcserver.proto

// Protobuf Java Version: 3.25.1
package com.maralana;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maralana_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maralana_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maralana_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maralana_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020grpcserver.proto\022\010maralana\"\034\n\014HelloReq" +
      "uest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007mess" +
      "age\030\001 \001(\t2E\n\007Greeter\022:\n\010SayHello\022\026.maral" +
      "ana.HelloRequest\032\024.maralana.HelloReply\"\000" +
      "B\'\n\014com.maralanaB\017HelloWorldProtoP\001\242\002\003HL" +
      "Wb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_maralana_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maralana_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maralana_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_maralana_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maralana_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maralana_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
